# .github/workflows/on_scanning_upload.yml
name: On Scanning File Upload - Log Received

on:
  push:
    paths:
      - 'conversation/csv/scanning.xlsx' # Folder name 'conversation' and file name 'scanning.xlsx'

jobs:
  log_received:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log Scanning.xlsx File Received
        run: |
          mkdir -p conversation/Logs || true # Ensure Logs directory exists
          echo "$(date +"%Y-%m-%d %H:%M:%S") - Scanning.xlsx file received." >> conversation/Logs/workflow_activity.log
          # NO git add, commit, push here.
