# .github/workflows/on_scanning_upload.yml
name: On Scanning File Upload - Log Received

on:
  push:
    paths:
      - 'conversation/csv/scanning.xlsx'

jobs:
  log_received:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log Scanning.xlsx File Received
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure token is available
        run: |
          mkdir -p conversation/Logs || true # Ensure Logs directory exists
          LOG_FILE="conversation/Logs/workflow_activity.log"
          echo "$(date +"%Y-%m-%d %H:%M:%S") - Scanning.xlsx file received." >> "$LOG_FILE"
          
          # Configure Git
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          
          # Stage the log file
          git add "$LOG_FILE"
          
          # Pull latest changes before committing to avoid conflicts. Rebase might be better here.
          git pull --rebase origin main || true # Use --rebase to apply local changes on top of remote
          
          # Commit the changes (only if there are actual changes to commit)
          if ! git diff --staged --quiet; then
              git commit -m "Log: Scanning.xlsx received."
          else
              echo "No changes to commit from log update."
          fi
          
          # Push the changes. Using --force-with-lease to handle potential race conditions safely.
          git push --force-with-lease || echo "Push failed for log update (Scanning.xlsx)."
